spring:
  application:
    name: FoodMood
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
  datasource:
    driverClassName: org.apache.commons.dbcp.BasicDataSource
    url: postgres://dqnyrgywjowsur:4DKeTXKrCov1n8PjFbAsa_22KC@ec2-54-228-219-2.eu-west-1.compute.amazonaws.com:5432/d43vsjt9ulorg3
    username: dqnyrgywjowsur
    password: 4DKeTXKrCov1n8PjFbAsa_22KC
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  context-path: /

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.example.school: INFO